const bcrypt = require('bcryptjs');
const { v4: uuidv4 } = require('uuid');
const fs = require('fs');
const path = require('path');

const db = {
  users: [
    {
      id: uuidv4(),
      username: 'admin',
      email: 'admin@dvfu-rectorat.ru',
      passwordHash: bcrypt.hashSync('admin123', 10),
      role: 'admin',
      createdAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      username: 'editor',
      email: 'editor@dvfu-rectorat.ru',
      passwordHash: bcrypt.hashSync('editor123', 10),
      role: 'editor',
      createdAt: new Date().toISOString(),
    },
  ],
  events: [
    {
      id: uuidv4(),
      type: 'event',
      title: 'Заседание Совета ректоров вузов ДФО',
      date: '15 ноября 2024',
      image: 'https://via.placeholder.com/600x350/1e4976/FFFFFF?text=Заседание',
      description: 'Состоялось очередное заседание Совета ректоров вузов Дальневосточного федерального округа. На повестке дня были рассмотрены вопросы развития научного потенциала региона и укрепления межвузовского сотрудничества.',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      type: 'news',
      title: 'Новое соглашение о сотрудничестве',
      date: '10 ноября 2024',
      image: 'https://via.placeholder.com/600x350/1e4976/FFFFFF?text=Соглашение',
      description: 'Подписано важное соглашение между вузами Дальневосточного федерального округа о совместных научных исследованиях и обмене студентами.',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      type: 'event',
      title: 'Международная конференция по образованию',
      date: '5 ноября 2024',
      image: 'https://via.placeholder.com/600x350/1e4976/FFFFFF?text=Конференция',
      description: 'Проведена масштабная международная конференция, посвященная современным тенденциям в высшем образовании. В мероприятии приняли участие представители ведущих университетов.',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      type: 'news',
      title: 'Новая программа поддержки молодых ученых',
      date: '1 ноября 2024',
      image: 'https://via.placeholder.com/600x350/1e4976/FFFFFF?text=Программа',
      description: 'Совет ректоров утвердил новую программу поддержки молодых ученых Дальневосточного федерального округа. Программа предусматривает гранты на научные исследования.',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      type: 'event',
      title: 'Круглый стол по цифровизации образования',
      date: '25 октября 2024',
      image: 'https://via.placeholder.com/600x350/1e4976/FFFFFF?text=Круглый+стол',
      description: 'Проведен круглый стол с участием руководителей IT-подразделений вузов по вопросам внедрения цифровых технологий в образовательный процесс.',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      type: 'news',
      title: 'Результаты конкурса студенческих проектов',
      date: '20 октября 2024',
      image: 'https://via.placeholder.com/600x350/1e4976/FFFFFF?text=Конкурс',
      description: 'Подведены итоги ежегодного конкурса студенческих проектов. Победители получили гранты на реализацию своих инициатив.',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  pressReleases: [
    {
      id: uuidv4(),
      title: 'Итоги заседания Совета ректоров ДФО',
      date: '15.11.2024',
      content: 'Краткое описание пресс-релиза...',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      title: 'Новая программа развития образования',
      date: '10.11.2024',
      content: 'Краткое описание пресс-релиза...',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      title: 'Подписание соглашения о сотрудничестве',
      date: '05.11.2024',
      content: 'Краткое описание пресс-релиза...',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  announcements: [
    {
      id: uuidv4(),
      title: 'Предстоящее заседание Совета ректоров',
      date: '25.11.2024',
      content: 'Информация о предстоящем мероприятии...',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      title: 'Международная конференция',
      date: '01.12.2024',
      content: 'Анонс международной конференции...',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  photos: [
    {
      id: uuidv4(),
      title: 'Заседание Совета ректоров',
      date: '15.11.2024',
      image: 'https://via.placeholder.com/400x300/1e4976/FFFFFF?text=Фото+1',
      published: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      title: 'Подписание соглашения',
      date: '10.11.2024',
      image: 'https://via.placeholder.com/400x300/1e4976/FFFFFF?text=Фото+2',
      published: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      title: 'Конференция по образованию',
      date: '05.11.2024',
      image: 'https://via.placeholder.com/400x300/1e4976/FFFFFF?text=Фото+3',
      published: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      title: 'Круглый стол',
      date: '01.11.2024',
      image: 'https://via.placeholder.com/400x300/1e4976/FFFFFF?text=Фото+4',
      published: true,
      createdAt: new Date().toISOString(),
    },
  ],
  videos: [
    {
      id: uuidv4(),
      title: 'Репортаж с заседания Совета',
      date: '15.11.2024',
      thumbnail: 'https://via.placeholder.com/400x250/1e4976/FFFFFF?text=Видео+1',
      videoUrl: '',
      published: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      title: 'Интервью с председателем',
      date: '10.11.2024',
      thumbnail: 'https://via.placeholder.com/400x250/1e4976/FFFFFF?text=Видео+2',
      videoUrl: '',
      published: true,
      createdAt: new Date().toISOString(),
    },
  ],
  documents: [
    {
      id: uuidv4(),
      category: 'История',
      title: 'История создания Совета ректоров вузов ДФО',
      file: 'history.pdf',
      date: '2020',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      category: 'История',
      title: 'Основные этапы развития',
      file: 'stages.pdf',
      date: '2021',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      category: 'Учредительные документы',
      title: 'Положение о Совете ректоров вузов ДФО',
      file: 'regulation.pdf',
      date: '2024',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      category: 'Учредительные документы',
      title: 'Устав Совета ректоров вузов ДФО',
      file: 'charter.pdf',
      date: '2024',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      category: 'Учредительные документы',
      title: 'Решение о создании Совета',
      file: 'decision.pdf',
      date: '2019',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      category: 'Решения Совета',
      title: 'Протокол заседания №12 от 15.11.2024',
      file: 'protocol_12.pdf',
      date: '15.11.2024',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      category: 'Решения Совета',
      title: 'Протокол заседания №11 от 10.10.2024',
      file: 'protocol_11.pdf',
      date: '10.10.2024',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: uuidv4(),
      category: 'Решения Совета',
      title: 'Протокол заседания №10 от 05.09.2024',
      file: 'protocol_10.pdf',
      date: '05.09.2024',
      published: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
};

fs.writeFileSync(
  path.join(__dirname, 'db.json'),
  JSON.stringify(db, null, 2),
  'utf-8'
);

console.log('База данных создана успешно!');
console.log('Пользователи:');
console.log('  admin / admin123 (администратор)');
console.log('  editor / editor123 (редактор)');
